### ISSUE TITLE
Mobile login

### ISSUE THREAD

**Issue by berserk82** [oneye/oneye#40]
Hello everyone. I tried to login oneye from an Android browser, but the submit button does nothing. I look at the code and everything looks right, so why can't I login? 
Plus, if I try to login with chrome for android, I have to add "android" to the list of user agents in index.php.

**Comment by lars-sh** [comment]
Would you like to get the desktop or one of the mobile versions?
I've no Android phone around to check that. My Edge on Windows 10 Mobile brings me to the desktop version and allows me to login successfully.
In order to reach either the "mobile" or the "iphone" versions manually, just enter one of both at the end of your URL.

**Comment by berserk82** [comment]
I would like to get the android browser version.
If I add the "android" user agent to the $mobile-cleints array, I can see the login screen for mobile (android version), but I can't login because the submit button doesn't work (even if in the code everything is fine).
Beside this, if I open oneye from the stock android browser, I can see the right login screen (which doesn't work), while if I use Chrome for android, I can see the desktop version (which works) unless I add "android" to the aforementioned array, in which case the login appears right but doesn't work.

**Comment by lars-sh** [comment]
For me that iPhone version is broken (I actually didn't maintain it any longer), but the mobile (when adding /mobile to the URL) should work as far as it's present.
