### ISSUE TITLE
https browsing

### ISSUE THREAD

**Issue by husseinmansour** [oneye/oneye#44]
I can't browse https website using navigator, only http sites.
Is there a fix to this issue?
thanks.

**Comment by Sable-oneye** [comment]
Hi,all questions have to be post on http://forums.oneye-project.org/Thanks
Le 2 avril 2017 à 10:57, Hussein Mansour <notifications@github.com> a écrit :I can't browse https website using navigator, only http sites.
Is there a fix to this issue?
thanks.

**Comment by lars-sh** [comment]
There are multiple things to take into account. Most are changed browser behaviour in order to secure the web browsing experience.

1. I guess you're using oneye via HTTP? Using HTTPS for oneye might help.
2. More and more developers prevent their sites from being opened inside an iFrame - for good reason.

I'm sorry, but nowadays the integrated browser isn't fully featured any longer. Sadly, but a good step towards better security.
