### ISSUE TITLE
Apps OnEye should have

### ISSUE THREAD

**Issue by berserk82** [oneye/oneye#45]
Hello everyone.
I guess OnEye should have these apps for production:
Formula (MathML) editor
Desktop Publishing
Personal finance manager
Personal DataBase
Diagram editor
File compare/merge
ID3 Tag editor
Project management
Zip [un]archiver
Batch renamer

Will someone add them, please?

Thanks in advance for either.

Bye, Ivano.

**Comment by lars-sh** [comment]
Hi Ivano,
currently there're not enough resources to fulfill your request. I'm sorry.

**Comment by anonimo82** [comment]
I'm interested, any news?
I also wish Google Drive/Microsoft OneDrive/Apple iCloud integration, to put files to.
Big thanks if you do.

**Comment by blackcrack** [comment]
Webdav in generally would nice as drive-letter in oneye :)
let the train become a hot boiler and steam it up/boil it up :) !

plugin-fs with webdav, and other possibility's like internal smb-fs where 
it is give the able to set up "Drive- letters"  also with google drives, local-fs in linuxhost and maybe OneDrive, ICloud ... 

a good suggestion/idea.. if this could be possible ...
because therewith could the users and Admins add his own drive-letter-path's

best regards
Blacky
