### ISSUE TITLE
PHP7 compatibility.

### ISSUE THREAD

**Issue by Ansem** [oneye/oneye#51]
How much of the script is incompatible with PHP7?
Since it doesn't rely on SQL it's limited, but are there any parts that need to be rewritten for PHP7?

**Comment by blackcrack** [comment]
@lars-sh  it's maybe possible to exist a script where checks the compatibility for PHP7
between more older php scripts ? makes the whole more easier for update the whole ..
Lars, i know, it's not any more you're head project but a bit update could be helpful, 
because php >7 is devilish fast today .. 
Also the thing with Homeworh, therewith could the Arbeitnehmer den Desktop in work and at home open it, if the EyeOS is the desktop for Companies with webtools like EGroupware and so on,
one login and the cookies could store inside in you're Eyeos-Browser and could open wnywhere, at home, in the works and in an other Land, therewith must not take with a Laptop, Easy connect
to the own Eyeos-login and have the whole Workspace open, include login-cookies in the Eyeos.
the EyeOS could today with PHP >7 more possibilitys and a more stronger crypting/tunnle ..
i think on the thor-browser as portable.. on a usb-stick .. 

well, a bit update on EyeOS could be helpful with >PHP7

@Ansem , can you PHP programming ?

best regards
Blacky

**Comment by lars-sh** [comment]
@Ansem Did you try running oneye with PHP7. I guess 99% should work without changing anything. In case it does not, report those cases as issue here at GitHub.
