### ISSUE TITLE
EyeDesigner + Code editor

### ISSUE THREAD

**Issue by anonimo82** [oneye/oneye#59]
EyeDesigner should be all you need to create Apps for OnEye, so, make it possible to write code with it too.

**Comment by anonimo82** [comment]
May be use Blockly for the logic application side?

https://developers.google.com/blockly

**Comment by chiaravalle** [comment]
What's EyeDesigner?

**Comment by lars-sh** [comment]
You can read some words about and download eyeDesignet from https://wiki.oneye-project.org/0.9:eyedesigner .

**Comment by blackcrack** [comment]
@lars-sh a Screenshoot would be helpful on the DL, because 1000 words ;)
@chiaravalle, could you make a screenshoot if you tested it and the png or jpg on the post move per mouse in the posting (p&p per mouse in your posting)
nice weekend :)

**Comment by anonimo82** [comment]
So, will this be in?
There could be System Designer used for the OOP part of this (https://designfirst.io/systemdesigner/)

**Comment by yortap** [comment]
Where I must put eyeDesigner.eyepackage ?

**Comment by lars-sh** [comment]
eyepackage files can be used just like an installer package: Upload the die to your oneye desktop and click it. You'll be asked whether eyeDesigner shall be installed.

**Comment by blackcrack** [comment]
oneeye becomes ever more interresting, because, like something.. 
https://webamp.org/
and, i have a own server running at home..  and have a running nextcloud but, 
would be cool, if i have also a Desktop over web... where maybe able to connect to my nextcloud instance, because
a Desktop with a taskbar and a startmenu is more better as a "WebSurface ...." 
also if i looking on eyeos.. well.. and if i look on Covit-19 and homework.. could oneye  have long since caught up..

imho a bit pitty ...

best

**Comment by anonimo82** [comment]
This is really OT, but FYI, you can check out FriendCloud [FriendCloud](https://friendsky.cloud/webclient/index.html), which works on mobiles too, and has a sort of package manager (which will evolve in a marketplace for buying Apps), other than an IDE for developing Friend Apps (Friend Create).
It's still in Alpha quality.

Cheers =)
